### ISSUE TITLE
Export : crash on big scenes ??

### ISSUE THREAD

**Issue by pandavigoureux29** [LadybugRiders/LREditor#22]
When I try to save my scene kimisrescue > level3_2, I go the error : 
 POST http://localhost:5000/editorserverapi/v0/level net::ERR_CONNECTION_RESET

1 > It seems it happens when I have too many entities in my scene. If I delete an entity I can then add another one and save successfully.

2 > The crash also happen when I set the "hideWhenOutOfView" of a group to true. This features basically sets the property hideWhenOutOfView of every entity in the group to true. If this value is set to false, it isn't written in the JSON, so setting it to true actually makes the JSON bigger ( not a lot )

The conclusion of these may be that the JSON we're trying to POST is too long and make angular crash.

NB : my valid JSON length is 88070 chars for now and it weights 86KB

**Comment by Mefteg** [comment]
Ok! It's a Post issue indeed. We have to send the json as a multipart data.
For now,  it is just a string.
Le 10 janv. 2015 06:58, "pandavigoureux29" <notifications@github.com> a
écrit :

**Comment by pandavigoureux29** [comment]
Okay. What does that imply ?

**Comment by Mefteg** [comment]
It implies the way we send the request from the editor and how the server
receives it. In a way, it's a good thing because it shows that we used an
easy solution until we reach the limit (which it reveals that we really use
our system). For me, it's the right thing to do. Now we have to rework it
but it's not a big deal.

2015-01-10 10:20 GMT-05:00 pandavigoureux29 <notifications@github.com>:
